trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH

- script: |
    # Update to Python 3.8 (defaults to 3.7, which is too old).
    conda install -y -c conda-forge 'python=3.8' pip
  displayName: 'Install Python 3.8'

- script: |
    # Installing dev version of asv to use new --strict option
    conda install -y -c conda-forge 'asv>=0.5'
  displayName: 'Install ASV'

- script: |
    cd dask
    asv machine --yes
    asv run --quick --show-stderr --strict
  displayName: 'Run Dask Benchmarks'

- script: |
    cd distributed
    asv machine --yes
    asv run --quick --show-stderr --strict
  displayName: 'Run Distributed Benchmarks'
